### ISSUE TITLE
Not working on Windows 9x

### ISSUE THREAD

**Issue by Haker120** [PluMGMK/rayman-tpls-tsr#1]
Win ME, v1.12 asks for Rayman CD, v1.21 unprotected works but plays wrong tracks everywhere, v1.12 with exe from v1.21 unprotected exe behaves like v1.21.
Running separately: TPLSTSR4.EXE forces me to ctrl + c to close window, music works but at startup logo plays third Band Land medalion music and Mr. Sax fight in main menu.
Running at the same dos mode: TSR is resident in memory but the same behavior.

Do I do something wrong? ME is a problem? I have to test with win 98 yet.

**Comment by PluMGMK** [comment]
[Issue renamed to indicate that this is specifically for Win9x]

OK, I've managed to test it on Windows 98, and I can confirm that my `int 2Fh` hook code is not getting run under Windows. I haven't figured out why yet, but it's because of this that it's not working for you.

It does work if I restart in MS-DOS mode though. The thing with running in pure DOS is that your CD drive needs to support playing audio CDs and its analogue output needs to be connected to the sound card, whereas this _may_ not be necessary under Windows 98…

**Comment by Haker120** [comment]
Ok, I tried clean DOS aka restart in DOS Mode and it's silent for me but TSR resides in memory.

**Comment by PluMGMK** [comment]
If it's silent that must mean there's no analogue connection between the CD drive and the sound card. Is it also silent if you play the game normally without the TSR?
Either way, I've figured out that Windows 9x intercepts all MSCDEX calls, preventing them from being routed to the TSR. I'm working on a solution, stay tuned...

**Comment by Haker120** [comment]
Well, with original CD no matter what machine I hear music and sounds, not just with Rayman. ;)

**Comment by PluMGMK** [comment]
Even in pure DOS? That is strange... Anyway, I'll keep working on Win9x support and we'll see if that solves the problem!

**Comment by Haker120** [comment]
Alright and pure DOS means reboot to DOS. :)

**Comment by PluMGMK** [comment]
OK, the latest commit should work on 98 / Me (but I haven't regression-tested it on normal DOS yet). Try this binary: [tplstsr4.exe.zip](https://github.com/PluMGMK/rayman-tpls-tsr/files/10439905/tplstsr4.exe.zip)

(Remember to run it from a DOS prompt and then run Rayman, double-clicking in Explorer won't work)

**Comment by Haker120** [comment]
I'm testing, I'll let you know. :)

**Comment by PluMGMK** [comment]
I haven't got anything like that on 98, would you be able to post screenshots of the errors? The only issue I'm having is that the hooks injected into Rayman's code only seem to work once, with the result that the music only changes the first time Rayman dies, instead of every time, and things like that. Maybe the problems are somehow related…

**Comment by Haker120** [comment]
My another crash on win98 caused the game to work with TSR so I cannot replicate that issue anymore, seems my installation was broken. Still v1.12EU doesn't work tho and asks for Rayman CD. Version that works is v1.12US unprotected (SoftKey release).

**Comment by PluMGMK** [comment]
So it's working now, at least with the unprotected one? That's good news! I'm still fine-tuning to fix the other problem I mentioned, and it still needs to be regression-tested. I'm currently testing with v1.20 German, which is fine, not sure why it's failing for v1.12EU…

**Comment by Haker120** [comment]
Honestly, if you need another exes I can provide, by years I was hunting for some version with full soundtrack so I happen to own lots of them, however, I'm not sure what versions I own. I even found (still waiting for family member to deliver as seller on ebay was sending only to GER) Rayman Platin Edition and few other. Also I guess just exe is required, I transplanted v1.12US unprotected to v1.12EU and it was working. :D Just let me know if that does make sense. :)

**Comment by PluMGMK** [comment]
Well, [the latest release](https://github.com/PluMGMK/rayman-tpls-tsr/releases/tag/v2.1) has been tested on Windows 98 and seems to work flawlessly (although I haven't completed the whole game with it…). If you still have issues, give me a shout (preferably with screenshots showing any errors) and I'll see what I can do.

Thanks for the offer of EXEs, it would be nice to add support for even more versions. I just need an EXE I can disassemble and find all the pointers for each one. Not now though, I feel I need a break from this for a while! :)

**Comment by Haker120** [comment]
Okay, I'll try to beat Rayman on this particular machine that works, v1.12US unprotected. :) I'll let you know if anything will happen.

**Comment by Haker120** [comment]
And it died with info:
![IMG_20230401_163441](https://user-images.githubusercontent.com/26009830/229295904-dd413e8b-a94b-4b4b-a6a5-8f47375ab796.jpg)

**Comment by PluMGMK** [comment]
Everything written there is normal, it's good that it's intercepting the Protected Mode entry. Does it just freeze at that point then? Maybe Win98SE does something that FE (which I tested on) didn't…

**Comment by Haker120** [comment]
Ok, I was messing with that PC, one thing was miscalled Rayman.EXE, second was... DVD drive had no pins for analog music, and last thing, installation of Win98SE was broken, now Rayman works with TPLSTSR and plays correct like PS1 soundtrack but on the other hand that new installation is super slow but that's HDD's problem so I guess will be ok to 'close with comment'. :D
