### ISSUE TITLE
Double "Yeah!" Sound

### ISSUE THREAD

**Issue by RibShark** [PluMGMK/rayman-tpls-tsr#4]
When the "yeah!" music plays at the end of a map, the sound effect still seems to play leading to a "doubled" sound.

**Comment by PluMGMK** [comment]
Yeah, that's a bit gammy all right. For some reason it didn't occur to me that I could fix it fairly easily (as per the commit above) until this issue motivated me to think about it a bit more! :sweat_smile: I'll do another minor release to address this shortly…

**Comment by RibShark** [comment]
It seems to crash DOSBox for me now sometimes (tested on 1.10 in Pink Plant Woods, crashed at Betilla screen exit)

**Comment by PluMGMK** [comment]
Oops… I'd better look at this more carefully then…

**Comment by PluMGMK** [comment]
I reckon the crash was probably caused by the `int 2Fh` callback trying to reactivate a hookpoint that no longer existed, so hopefully the commit above addresses that…
